apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: crosswalksignals.safety.traffic.bwarminski.io
spec:
  group: safety.traffic.bwarminski.io
  names:
    kind: CrosswalkSignal
    plural: crosswalksignals
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            flashingHandDurationSec:
              format: int64
              type: integer
            greenLightBufferDurationSec:
              format: int64
              type: integer
            stoplight:
              type: string
          type: object
        status:
          properties:
            lastTransition:
              format: int64
              type: integer
            symbol:
              type: string
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
