apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - safety.traffic.bwarminski.io
  resources:
  - crosswalksignals
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - safety.traffic.bwarminski.io
  resources:
  - stoplights
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - safety.traffic.bwarminski.io
  resources:
  - stoplights
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - safety.traffic.bwarminski.io
  resources:
  - ambulances
  verbs:
  - get
  - list
  - watch
